version: '3.8'

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Passw0rd!"
      ACCEPT_EULA: "Y"
    volumes:
      - sql-data:/var/opt/mssql
      
    depends_on:
      - init-db

  init-db:
    image: mcr.microsoft.com/mssql-tools
    volumes:
      - ./Database:/scripts
    command: sh -c "/scripts/make_db.sh"

volumes:
  sql-data: