Use PlugAndPlay

ALTER TABLE BMA_FIELD_SCHEMA
ADD Parent int;

ALTER TABLE BMA_FIELD_SCHEMA
ADD CONSTRAINT [FK_BMA_FIELD_SCHEMA_BMA_FIELD_SCHEMA_FieldSchemaId] FOREIGN KEY ([Parent]) REFERENCES [dbo].[BMA_FIELD_SCHEMA] ([Id]);